FROM node:22-bookworm-slim AS build

WORKDIR /app

COPY . .

RUN corepack pnpm install --frozen-lockfile

ARG NEXT_PUBLIC_API_URL
ENV NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}

RUN corepack pnpm build


FROM node:22-bookworm-slim AS runtime

ENV NODE_ENV=production
ENV PORT=3000

WORKDIR /app

COPY --from=build /app /app

EXPOSE 3000

CMD ["corepack", "pnpm", "--filter", "@integrador/web", "start"]